apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: otel-collector
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/thisthat/progressivedelivery-masterclass.git'
    targetRevision: main
    path: "gitops/manifests/otel-collector"
  destination:
    namespace: keptn-lifecycle-toolkit-system
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true