apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: prometheus-crds
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/thisthat/progressivedelivery-masterclass.git'
    targetRevision: main
    path: "gitops/manifests/prometheus-crds"
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true      